// export const COMMON = {
//     LOAD: "COMMON_LOAD",
//     LOADED: "COMMON_LOADED",
//     FINALLY: "COMMON_FINALLY"
// }

export const LOGIN = {
    SUBMIT: "LOGIN_SUBMIT",
    GET_ACCESS_TOKEN: "LOGIN_GET_ACCESS_TOKEN",
    REFRESH_ACCESS_TOKEN: "LOGIN_REFRESH_ACCESS_TOKEN",
    HAS_BINDED: "LOGIN_HAS_BINDED",

}


// export const ORDER_LIST = {
//     GET_MENUS: "ORDER_LIST_GET_MENUS",
//     GET_TITLE: "ORDER_LIST_ GET_TITLE",
//     GET_LIST: "ORDER_LIST_ GET_LIST",
//     ASSIGN_TICKET: "ORDER_LIST_ASSIGN_TICKET",
//     SET_CURRENT_MENU: "ORDER_LIST_SET_CURRENT_MENU",
//     GET_ORDER_PARAM: "ORDER_LIST_GET_ORDER_PARAM",
// }

// // 创建工单
// export const ORDER = {
//     // USER_NAME: 'ORDER_USER_NAME',
//     // USER_PHONE: 'ORDER_USER_PHONE',
//     ORDER_TYPE: 'ORDER_ORDER_TYPE',
//     PROB_TYPE: 'ORDER_PROB_TYPE',
//     PRIORITY: 'ORDER_PRIORITY',
//     SOURCE: 'ORDER_SOURCE',
//     PAGE_INFO: 'ORDER_PAGE_INFO',
//     SUBMIT: 'ORDER_SUBMIT'

// }